    name: Ping Supabase to Prevent Pausing

    on:
      schedule:
        - cron: '0 9 * * 1,4' # 매주 월요일과 목요일 오전 9시 UTC에 실행
      workflow_dispatch: # GitHub UI에서 수동으로 실행 가능

    jobs:
      ping:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '18' # Node.js 버전 지정

          - name: Install Supabase Client
            run: npm install @supabase/supabase-js --force

          - name: Ping Supabase
            env:
              SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} # Supabase 프로젝트 URL
              SUPABASE_KEY: ${{ secrets.NEXT_SERVICE_ROLE_KEY }}   # Supabase 서비스 역할 키
            run: |
              node -e "
              (async () => {
                try {
                  const { createClient } = require('@supabase/supabase-js');
                  const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

                  // 'your_table'을 실제 테이블 이름으로 변경하거나, 간단한 쿼리로 대체 가능
                  const { data, error } = await supabase.from('schedules').select('*').limit(1);

                  if (error) throw error;
                  console.log('Supabase ping successful:', data);
                } catch (err) {
                  console.error('Error pinging Supabase:', err.message);
                  process.exit(1);
                }
              })();
              "